{% set version = "0.5.2" %}
{% set pkg_name = "patsy" %}


package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: 5053de7804676aba62783dbb0f23a2b3d74e35e5bfa238b88b7cbf148a38b69d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.4.0
    - scipy
    - six

test:
  imports:
    - patsy

about:
  home: https://github.com/pydata/patsy
  license: BSD-2-Clause, PSF-2.0
  license_file: LICENSE.txt
  summary: Describing statistical models in Python using symbolic formulas

extra:
  recipe-maintainers:
    - bollwyvl
    - croth1
