{% set version = "0.5.3" %}
{% set pkg_name = "patsy" %}


package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: bdc18001875e319bc91c812c1eb6a10be4bb13cb81eb763f466179dca3b67277

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.4.0
    - scipy
    - six

test:
  imports:
    - patsy

about:
  home: https://github.com/pydata/patsy
  license: BSD-2-Clause AND PSF-2.0
  license_family: BSD
  license_file: LICENSE.txt
  summary: Describing statistical models in Python using symbolic formulas

extra:
  recipe-maintainers:
    - bollwyvl
    - croth1
