{% set version = "0.5.0" %}
{% set pkg_name = "patsy" %}


package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: e05f38d5c38c8d216f0cc2b765b1069b433c92d628b954fb2fee68d13e42883b

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy >=1.4.0
    - scipy
    - six

test:
  imports:
    - patsy

about:
  home: https://github.com/pydata/patsy
  license: BSD-2-Clause, PSF2
  license_family: BSD
  license_file: LICENSE.txt
  summary: Describing statistical models in Python using symbolic formulas

extra:
  recipe-maintainers:
    - bollwyvl
    - croth1
