travis:
  secure:
    BINSTAR_TOKEN: eca5IJBgbQpp+hblmSQJIxRtWP4z8PBP6ZYAqMz4CW8aqoE4RKPKL+E358zaUt4Mt8aVOR/EVMDolH9e6bnAa7k9BQedYhZmEG7HdgLMaZz7ytCe14qwGIlOzIcz9SSA3yBJn2Yacv36bZQPnT/O4LtZb9ICSQVFxz94ZI2Y2eDxPbhv3ms78WYCzu+8DQePotJk93atB48LbIBBxeOOLyacLY0+FVnfwf7KE74VN0IMRWBFW7B5iiO0wIMHXRz3DyV3A8gFc5u3lceKvx6S74tdh7tGRiXfWTVYSJgW37GpbAJbXzwtdAzDWN9xyak04qRcjM0Y7xYp04ZiAH2THfHCOy1S5lxfy6bVuOF28Nggyen2tqecRB35oXtPZDMpTCLi2GZrIUDZe/hTZSJ+KwMZgcrBssrjVLJ5kNJH6Gz8mwETZzsMQo88kYMXPiI0wzYWdo2AmLEDgNgZe/hUNFagg9z3K+4Q0327IrkjkYwegqw2pDwRNbOZusKbh+KL7K7XxpBFx4zv5VKm55G4qKmHdqulhDPaySwqvy0v3R3IbZXfsmdoKvmi+NxiN/defjl8ovmArcFaT15ZTCxaWC/1C3cPgi6xcdKau9EJlf98mn2ttmEn92L8XRxZY5stUyT7q4cOZFvsdfr4TtMcSWTbN+eA9c2YnKLO5DurNhc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
