travis:
  secure:
    BINSTAR_TOKEN: Jj4h9F/dDjdFnRpZyBpvBMltSs42WM6IpnfwPxRGIpaSsN3kBcw+fU+XOmGf8nOSW5Ryc56dQC49Lwty9AU1Mbqkdss1zTdYRLS8Xt31p7+4rG1Rk0nrz+HUv8pdpa4GDeVOwVpoU9yPsI7huYOSXwAv0mZ/cvxzBVBG0b3GcNYxsyjiFEJcmQUhyfoOALYbrhLMYWcP9v4RfJam1qcot0QyUbO1n7ETZzu2RRKW8Rd2NIwHJy52ud94akhpDVni//yyRql98NC9zgQQ5v65P/cVJxYyOE4mXqqIYF7B6cp8wbt2z0byPGwEF+8GIU4KRAhybcU6JbY8E/5wbi8Qm5iZjJAHvv/yTUgfQo89NQkbr8bu5oalGrULvB/hv9zCaJ0NLkLJz1wARqIU6tQhk+tdGkUjoc0HAnMFSvcXmpS0wpO48ocenZ2awNHf7EJs8gQz039NYlOZt/KpgNyNODuyCl0Cm7dkx0etNH6XDWLKODfZLk3clEGOZ0W9nCWAtSDneaz7HGr3p4PSsZ7c+HgZWT6o634uOvUJtYk196G3O1PjlHpTdfunhoHMw4b07NZPv23R5EivGJLGnz6wg/TkNhnpZDgRLSffqqCJ6TYIbVIiGHZP5RCH8tDM5CKAN13wCM9gLkXwA+ifzBMzz2eckb3JbldXSBQt5B8WC4g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
